package com.booboot.vndbandroid.model.vndbandroid

import com.booboot.vndbandroid.R

object Platform {
    val FULL_TEXT = mapOf(
            "win" to "Windows",
            "dos" to "DOS",
            "lin" to "Linux",
            "mac" to "Mac OS",
            "ios" to "Apple iProduct",
            "and" to "Android",
            "dvd" to "DVD Player",
            "bdp" to "Blu-ray Player",
            "fmt" to "FM Towns",
            "gba" to "Game Boy Advance",
            "gbc" to "Game Boy Color",
            "msx" to "MSX",
            "nds" to "Nintendo DS",
            "nes" to "Famicom",
            "p88" to "PC-88",
            "p98" to "PC-98",
            "pce" to "PC Engine",
            "pcf" to "PC-FX",
            "psp" to "PlayStation Portable",
            "ps1" to "PlayStation 1",
            "ps2" to "PlayStation 2",
            "ps3" to "PlayStation 3",
            "ps4" to "PlayStation 4",
            "psv" to "PlayStation Vita",
            "drc" to "Dreamcast",
            "sat" to "Sega Saturn",
            "sfc" to "Super Nintendo",
            "wii" to "Nintendo Wii",
            "n3d" to "Nintendo 3DS",
            "x68" to "X68000",
            "xb1" to "Xbox",
            "xb3" to "Xbox 360",
            "xbo" to "Xbox One",
            "web" to "Website",
            "oth" to "Other"
    )
    val IMAGES = mapOf(
            "win" to R.drawable.win,
            "dos" to R.drawable.dos,
            "lin" to R.drawable.lin,
            "mac" to R.drawable.mac,
            "ios" to R.drawable.ios,
            "and" to R.drawable.and,
            "dvd" to R.drawable.dvd,
            "bdp" to R.drawable.bdp,
            "fmt" to R.drawable.fmt,
            "gba" to R.drawable.gba,
            "gbc" to R.drawable.gbc,
            "msx" to R.drawable.msx,
            "nds" to R.drawable.nds,
            "nes" to R.drawable.nes,
            "p88" to R.drawable.p88,
            "p98" to R.drawable.p98,
            "pce" to R.drawable.pce,
            "pcf" to R.drawable.pcf,
            "psp" to R.drawable.psp,
            "ps1" to R.drawable.ps1,
            "ps2" to R.drawable.ps2,
            "ps3" to R.drawable.ps3,
            "ps4" to R.drawable.ps4,
            "psv" to R.drawable.psv,
            "drc" to R.drawable.drc,
            "sat" to R.drawable.sat,
            "sfc" to R.drawable.sfc,
            "wii" to R.drawable.wii,
            "n3d" to R.drawable.n3d,
            "x68" to R.drawable.x68,
            "xb1" to R.drawable.xb1,
            "xb3" to R.drawable.xb3,
            "xbo" to R.drawable.xbo,
            "web" to R.drawable.web,
            "oth" to R.drawable.oth
    )
}
