# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    lane :build do |options|
        gradle(task: "assembleRelease")
    end

    def blank(value)
        value !~ /[^[:space:]]/
    end

    desc "Deploy a new version to Google Play"
    lane :deploy do
        upload_to_play_store
    end

    def get_aapt_property(properties, property_name)
        sh("echo \"#{properties}\" | sed 's/.*#{property_name}=.\\([a-zA-Z0-9\\.]*\\).*/\\1/g' | tr -d '[:space:]'", log: false)
    end
end